### PR TITLE
Add reddit forum link to the home page

### PR DESCRIPTION
**Pull request by lucasprag**
Move social links to footer and aligh navbar links to the right

This is needed so we can have more links in the navbar such as the code
of conduct (to be added) and others.

Also, I change the container in the navbar to not be fluid.

## Before:
Screen Shot 2019-12-30 at 8 24 51 AM

## After: 
Screen Shot 2019-12-30 at 8 51 12 AM

Thanks =)

### CODE REVIEW

**Comment by lucasprag** [comment]
Since this PR was open I added one more commit which:
- add a link to our sub reddit and its chat room
- add SVGs for the reddit and meetup logos

Some screenshots in different screen sizes:

Screen Shot 2019-12-30 at 12 35 56 PM
Screen Shot 2019-12-30 at 12 36 07 PM
Screen Shot 2019-12-30 at 12 36 20 PM
Screen Shot 2019-12-30 at 12 36 30 PM

**Comment by lucasprag** [comment]
I updated it to not say anything about a chat just yet since we are going to do Matrix (see https://github.com/kwruby/kwruby.ca/issues/1#issuecomment-570968720).

Screen Shot 2020-01-05 at 9 36 13 PM

**Comment by acant** [comment]
@lucasprag thank you for all the great PRs! I really appreciate that you have been creating the screenshots, because it makes it really easy to review what the change will do.

After merging in the code of conduct from #47, this PR needs resolution. :) Can you resolve it? I can do it on the weekend, if you do not have an opportunity.

I will get the matrix stuff setup and then we can, figure out the best way to link it, too!

Thanks again for your work @lucasprag it is much appreciated!

**Comment by lucasprag** [comment]
Awesome, thank you, I really appreciate your work maintaining this community =)
The conflict is gone 🎉 

Firefox:
Screen Shot 2020-01-09 at 9 21 02 AM

Google Chrome:
Screen Shot 2020-01-09 at 9 21 13 AM

**Comment by acant** [comment]
I am not sure why the rebase could not be done in the UI, but I followed the CLI instructions and did the rebase and merge manually. The site has been automatically re-built, and the changes are being displayed!

**Comment by lucasprag** [comment]
Awesome, thanks =)

**Pull request closed without merging**
