### PR TITLE
Refactor website to make it simpler and to remove dependencies

### PR DESCRIPTION
**Pull request by lucasprag**
Hi @acant  =)

The goal of this PR is to make it easier for people to contribute to this website by:
  - making this website super simple
  - using CSS as minimal as possible -- no mixins, media queries, etc, only simple sass css
  - using more popular technologies, like twitter bootstrap

Removed dependencies:
- custom JS code
- `neat` -- we were using v1.80, current version is 4.0.0
- `font-awesome-middleman` -- not been used
- `bitters`
- `bourbon`
- `devicon` -- `https://cdn.rawgit.com/konpa/devicon/master/devicon.min.css`

Home page:

Screen Shot 2019-10-30 at 1 27 31 AM

Screen Shot 2019-10-30 at 1 29 56 AM

Wiki pages:

Screen Shot 2019-10-30 at 1 36 43 AM

Screen Shot 2019-10-30 at 1 36 58 AM

Screen Shot 2019-10-30 at 1 36 08 AM

Screen Shot 2019-10-30 at 1 36 21 AM

I hope this isn't too much for a single PR, I tried to get the website to a closer state with the current designs but simpler code. My intention is to contribute more by doing some of the issues like the one to automate deployment and add more content later to get people more excited about these workshops. Also I'd like to add a new logo strongly inspired in the current one which is still there even thought it's not in the navbar.

I'm totally open for feedback even if the feedback is to throw it all away 👍 

Thanks for reviewing @acant =)

### CODE REVIEW

**Comment by acant** [comment]
@lucasprag the screenshots look really nice, and I do love removing code and simplifying things.
I want to try building this locally, and do a quick review and then I will merge it.

**Comment by lucasprag** [comment]
@acant, thanks. I forgot to mention, but I changed it to use [Bootstrap's CDN](https://github.com/kwruby/kwruby.ca/pull/43/files#diff-2f7bf87f3f0b590ba1e915784cbf1e0eR15) instead of having a gem/package installed. I hope this is not a problem, but I'm open for feedback, thanks =)

**Comment by acant** [comment]
Oops, I just merged and then unmerged, because there is an error when building. :)

But otherwise I really like the change. :+1:  I tried to do too many new things all at once, making it hard for other to contribute. I can save that for my own website!

So some details....when I run `bundle exec middleman build` there is an error related to CSS:
```
/home/andrew/joined/github.com/kwruby/kwruby.ca.git/source/stylesheets/base.scss:2: Undefi
ned variable: "$white". (Sass::SyntaxError)
  (in /home/andrew/joined/github.com/kwruby/kwruby.ca.git/source/stylesheets/base.scss:2)
```

Maybe just an ordering problem in the CSS?

**Comment by lucasprag** [comment]
Thanks for pointing it out @acant, the problem was that I had the base css file without the `_` meaning that it should include all its dependencies. Since I'm only using one css file as entrypoint for all css I just added the `_` to it.

I created a new PR with my existing branch and fix: https://github.com/kwruby/kwruby.ca/pull/45

Thank you =)

**Comment by acant** [comment]
:+1: I just merged your branch into master, and deployed. It looks very nice.
(I still needed to re-set the domain name after deploy. Still need to figure that out.)

**Comment by lucasprag** [comment]
Awesome, thanks =D I can help you with that tomorrow @acant

**Pull request merged**
